# Generated by Django 5.1.1 on 2024-10-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
