# Generated by Django 5.1.1 on 2024-10-31 11:19

import phonenumber_field.modelfields
import tution.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IN', validators=[tution.models.valnum]),
        ),
    ]
