# Generated by Django 5.1.1 on 2024-11-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0005_student_teacher_alter_student_user_stdattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdattendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tution.student'),
        ),
    ]
