# Generated by Django 5.1.1 on 2024-11-05 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0007_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdffiles/')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tution.student')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tution.task')),
            ],
            options={
                'unique_together': {('student', 'task')},
            },
        ),
    ]
