# Generated by Django 5.1.1 on 2024-11-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0008_stask'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stask',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='tution.task'),
        ),
    ]
